trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# 🔥 ВАЖНО: използваме glob вместо твърд path
- script: dotnet restore **/*.sln
  displayName: 'Restore'

- script: dotnet build **/*.sln --configuration Release
  displayName: 'Build'

- script: dotnet test **/*.sln --configuration Release --no-build
  displayName: 'Test'